### ISSUE TITLE
getPlayerMMR not correctly returning LatestCompetitiveUpdate

### ISSUE THREAD

**Issue by Lunium** [liamcottle/valorant.js#11]
When you use the getPlayerMMR call to get the MMR data of a player, and that player hasn't played a Competitive game as his last played game. Then the LatestCompetitiveUpdate will not have that player's latest competitive update.

Expected behavior would be that the LatestCompetitiveUpdate would always be filled with the latest competitive update. 

**For instance:** If a player has played a Deathmatch game as his latest game, this method will be useless as it shows the info of the Deathmatch game. Which means that there is no MMR data for that player.

**Comment by liamcottle** [comment]
Unfortunately that's how that specific VALORANT API was coded by Riot.

This isn't an issue with this library, that's just the data returned directly from the API.

An alternative would be to use one of the other endpoints which returns a list of historical matches, in which case you could then iterate over them and check the match game mode is the one you want.
