### ISSUE TITLE
getContent() returns a 404 when called

### ISSUE THREAD

**Issue by Lunium** [liamcottle/valorant.js#12]
getContent() returns a 404 when called.

```
data: {
      httpStatus: 404,
      errorCode: 'UNKNOWN_CONTENT_VERSION',
      message: 'unknown version requested'
    }
```

I expect this issue occurs because the v2 of the api is called.
The v1 of the api should probably be used.
https://developer.riotgames.com/apis#val-content-v1/GET_getContent

**Comment by Kavan72** [comment]
@Lunium working perfect, it's a game api. you need to update game version in headers

**Comment by liamcottle** [comment]
> The v1 of the api should probably be used.

This library uses the in game private apis, and not the public apis in the documentation you linked.

For this specific issue, you can grab the latest game client version and set it like so:

```
const Valorant = require('@liamcottle/valorant.js');
const valorantApi = new Valorant.API(Valorant.Regions.AsiaPacific);
valorantApi.client_version = 'release-02.01-shipping-6-511946';
```

I don't have the latest version on me, but you can get it from game logs.

> Note: this issue will happen everytime VALORANT updates their game and prevents older versions from working.

**Comment by Kavan72** [comment]
you can grab client latest version from my repo. It'll update automatic everytime when client got update. 
https://github.com/Kavan72/valorant-versioning
