### ISSUE TITLE
400 Bad Request: invalid_session_id

### ISSUE THREAD

**Issue by Tiqan** [liamcottle/valorant.js#20]
If i try to authorize i get a 400 response with 
```
{
   "type":"error",
   "error":"invalid_session_id",
   "country":"deu"
}
```

Request URL: https://auth.riotgames.com/api/v1/authorization
Request Method: PUT
Status Code: 400 
Request Payload:
```
{type: "auth", username: "XXXXXXXXXXXXXXX", password: "XXXXXXXXXX"}
```

Do you know why?

**Comment by texasrodeo** [comment]
Hi, did you manage to resolve this issue?

**Comment by Tiqan** [comment]
No sorry... But I figured out that I had this error because my electron-react-app wasnt saving the cookies right... The tough-cookie package seems like not working with my electron-react-app
