### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by liamcottle** [liamcottle/valorant.js#21]
A `403 Forbidden` error is received when attempting to log in.

The log in flow will need to be proxied to intercept the auth requests, and then the auth requests in the library will need to be updated.

I don't have the time for this right now, but feel free to check it out if you're here.

**Comment by SpatzlHD** [comment]
If you want i can rewrite the auth system to fix the error

**Comment by SpatzlHD** [comment]
I opened a Pull Request with a Fix

**Comment by liamcottle** [comment]
Fixed by https://github.com/liamcottle/valorant.js/pull/22
