### ISSUE TITLE
How can I use this in python?

### ISSUE THREAD

**Issue by vismodo** [liamcottle/valorant.js#27]
I want to use this library in Python. Are there any URLs I can make requests to to authenticate the user etc? Thanks

**Comment by SpatzlHD** [comment]
This is as JavaScript libary but if you need help using the unoffical client api maby join https://discord.gg/3ESyfUfWM7 they will probably help you with your questions

**Comment by vismodo** [comment]
> This is as JavaScript libary but if you need help using the unoffical client api maby join https://discord.gg/3ESyfUfWM7 they will probably help you with your questions

Invalid link. Also, I am aware this is a JS library but I want to replicate it in py

**Comment by SpatzlHD** [comment]
If you whant to build something on your own maby take a look at https://github.com/techchrism/valorant-api-docs/ it is a bit of a documentation for the API

**Comment by SpatzlHD** [comment]
And for me the link works completely fine
