### ISSUE TITLE
403 Forbidden error while trying to authenticate

### ISSUE THREAD

**Issue by atitkh** [liamcottle/valorant.js#28]
While trying to use valorantApi.authorize(username, password), there is an error with code 403 Forbidden.

**Comment by SpatzlHD** [comment]
That is probably coused by riot updating there Cloudfair settings again...
There are a few new workarounds that I am trying to fix the problem.
@liamcottle if you whant you can assign this issue to me

**Comment by SpatzlHD** [comment]
until the patch is published you can manuel set the new client_version and user_agent by using
```js
valorantApi.user_agent = "RiotClient/58.0.0.4640299.4552318 %s (Windows;10;;Professional, x64)"
valorantApi.client_version = "release-05.06-shipping-6-765767"
```
before calling the `valorantApi.authorize` methode.
This should fix the error

**Comment by atitkh** [comment]
Working after changing the versions, thanks!
