### ISSUE TITLE
I can't authorize my account.

### ISSUE THREAD

**Issue by Infinity9591** [liamcottle/valorant.js#31]
I use your API to write discord bot exactly like your example but got 403 error. I'm new to programming so I don't know where I went wrong and how to fix it. I installed your API and here is the code and error I got.
Hope to receive your reply soon.
![image](https://user-images.githubusercontent.com/106311029/202835331-92dcad7e-2cf1-43f2-957a-413b30fabd6a.png)
![image](https://user-images.githubusercontent.com/106311029/202835358-bcefcccd-a74f-4499-ae7a-93484a338159.png)

**Comment by rjames1295** [comment]
I'm not too familiar with Riot's internal API workings, but perhaps the `user_agent` header value is outdated?

https://github.com/liamcottle/valorant.js/blob/09176a77e77eb93eb2370571d6828f5ee95b8f6a/src/api.js#L36

@liamcottle

**Comment by SpatzlHD** [comment]
You can try to update the useragent and clientversion
```js
vlrapi.user_agent = "RiotClient/60.0.10.4802528.4749685 rso-auth (Windows;10;;Professional, x64)";
vlrapi.client_version = "release-05.10-shipping-11-796984";
```

**Comment by Infinity9591** [comment]
Nah, I have another issue. I cant get Bundle ID, please help me. ;-;

**Comment by Infinity9591** [comment]
Uhhh... I want to link my account to my Discord account, pls help me. ;-;
