### ISSUE TITLE
code:ECONNRESET how can i fix it

### ISSUE THREAD

**Issue by AprDeci** [liamcottle/valorant.js#35]
it seems is tls problem
```
<ref *1> Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1590:19)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
 code: 'ECONNRESET',
  path: null,
  host: 'auth.riotgames.com',
  port: 443,
  localAddress: undefined,
```

**Comment by SpatzlHD** [comment]
@q1263868407 can you maybe provide some code that you use to authenticate

**Comment by AprDeci** [comment]
> @q1263868407 can you maybe provide some code that you use to authenticate

yes.
` client.authorize(username,password).then(() => {
    client.getPlayerStoreFront(client.user_id).then(async (response) => {

}`
I also push it in my repository called valorant-tgbot

**Comment by SpatzlHD** [comment]
Thanks I will test it out when I am at home

**Comment by SpatzlHD** [comment]
@q1263868407 i dont think this repo is public because i cant find it on your profile

**Comment by AprDeci** [comment]
> @q1263868407 i dont think this repo is public because i cant find it on your profile

https://github.com/q1263868407/Valorant-storefront-bot
actually I spell wrong it's name
